name: langchain

dependencies:
  - python=3.10.12
  - pip
  - pip:
    - langchain==0.0.267
    - openai==0.27.8
    - jupyter==1.0.0
    - python-dotenv==1.0.0
    - chromadb==0.4.6
    - tiktoken==0.4.0
    - azure-cosmos==4.5.0